spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:soccer}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8081

springdoc:
  api-docs.path: /v1/api-docs
  swagger-ui.path: /v1/swagger
